import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Montserrat', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Montserrat', ...defaultTheme.fontFamily.sans],
                'headline-lg-mobile': ['Montserrat', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Montserrat', ...defaultTheme.fontFamily.sans],
                'title-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'body-md': ['Inter', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Inter', ...defaultTheme.fontFamily.sans],
                'label-md': ['Inter', ...defaultTheme.fontFamily.sans],
                caption: ['Inter', ...defaultTheme.fontFamily.sans],
                'display-lg': ['Montserrat', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
                caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
            },
            spacing: {
                'container-max-width': '1200px',
                'margin-desktop': '32px',
                'margin-mobile': '16px',
                gutter: '24px',
                'stack-sm': '8px',
                'stack-md': '16px',
                'stack-lg': '32px',
            },
            colors: {
                'primary-container': '#c8102e',
                'on-background': '#1b1c1c',
                'primary-fixed': '#ffdad8',
                error: '#ba1a1a',
                'inverse-primary': '#ffb3b1',
                'surface-container-low': '#f6f3f2',
                primary: '#9e001f',
                'on-primary-fixed-variant': '#92001c',
                'on-secondary-fixed': '#002107',
                'surface-container': '#f0eded',
                'secondary-container': '#7ff98d',
                'on-tertiary': '#ffffff',
                'error-container': '#ffdad6',
                'secondary-fixed-dim': '#65df76',
                'tertiary-fixed-dim': '#f1c100',
                'secondary-fixed': '#81fc90',
                'on-tertiary-fixed': '#241a00',
                tertiary: '#745b00',
                'inverse-surface': '#303030',
                'surface-bright': '#fbf9f8',
                surface: '#fbf9f8',
                secondary: '#006e27',
                'on-tertiary-container': '#4f3d00',
                'on-error': '#ffffff',
                'tertiary-fixed': '#ffe08a',
                'on-error-container': '#93000a',
                'on-primary-fixed': '#410007',
                'on-secondary-container': '#007329',
                'surface-dim': '#dcd9d9',
                'on-primary-container': '#ffdad8',
                'on-surface-variant': '#5c403f',
                outline: '#906f6e',
                'primary-fixed-dim': '#ffb3b1',
                'outline-variant': '#e5bdbb',
                background: '#fbf9f8',
                'on-surface': '#1b1c1c',
                'surface-variant': '#e4e2e1',
                'surface-container-highest': '#e4e2e1',
                'on-tertiary-fixed-variant': '#574400',
                'tertiary-container': '#d0a600',
                'on-primary': '#ffffff',
                'surface-tint': '#bf0229',
                'on-secondary': '#ffffff',
                'surface-container-high': '#eae7e7',
                'on-secondary-fixed-variant': '#00531c',
                'inverse-on-surface': '#f3f0f0',
                'surface-container-lowest': '#ffffff',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
        },
    },
    plugins: [forms],
};
